export const GET_DOCUMENT_LIST_REQUEST = 'GET_DOCUMENT_LIST_REQUEST';
export const GET_DOCUMENT_LIST_SUCCESS = 'GET_DOCUMENT_LIST_SUCCESS';
export const SET_DOCUMENT_STATUS = 'SET_DOCUMENT_STATUS';
export const UPDATE_MY_CHECK_LIST = 'UPDATE_MY_CHECK_LIST';
