export const GET_DOCUMENT_LIST_REQUEST = 'GET_DOCUMENT_LIST_REQUEST';
export const GET_DOCUMENT_LIST_SUCCESS = 'GET_DOCUMENT_LIST_SUCCESS';
export const SET_DOCUMENT_STATUS = 'SET_DOCUMENT_STATUS';
export const UPDATE_MY_CHECK_LIST = 'UPDATE_MY_CHECK_LIST';
export const DELETE_MY_CHECK_LIST = 'DELETE_MY_CHECK_LIST';
export const UPDATE_PERSONAL_ITEM = 'UPDATE_PERSONAL_ITEM';
export const DELETE_PERSONAL_ITEM = 'DELETE_PERSONAL_ITEM';
